name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
